#!/bin/sh

set -e

WORKDIR=$AUTOPKGTEST_TMP
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM

cd $WORKDIR

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    CROSS_COMPILE="$DEB_HOST_GNU_TYPE-"
else
    CROSS_COMPILE=
fi

cat <<EOF > libeis-build.c
#include <libeis.h>

int main()
{
    struct eis *eis = eis_new(NULL);
    eis_unref(eis);

	return 0;
}
EOF

${CROSS_COMPILE}gcc -Wall -Werror -o libeis-build libeis-build.c `${CROSS_COMPILE}pkg-config --cflags --libs libeis-1.0`
echo "libeis build: OK"
[ -x libeis-build ]
./libeis-build
echo "libeis run: OK"
